version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "715841362372"
    AWS_DEFAULT_REGION: us-west-2
    TF_VERSION: "1.6.6"
    TERRAFORM_ACTION: "apply"
  parameter-store:
    DB_PASSWORD: /cloudops-demo/db-password

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Terraform...
      - mkdir -p /tmp/terraform_install
      - wget -O /tmp/terraform_install/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o /tmp/terraform_install/terraform.zip -d /tmp/terraform_install/
      - mv /tmp/terraform_install/terraform /usr/local/bin/
      - rm -rf /tmp/terraform_install
      - terraform --version

      - echo Installing AWS CLI...
      - pip install --upgrade awscli
      - aws --version
      - echo Verifying git availability...
      - git --version


  pre_build:
    commands:
      - cd terraform

      - echo Configuring Terraform backend...
      - echo "terraform {" > backend.tf
      - echo "  backend \"s3\" {" >> backend.tf
      - echo "    bucket         = \"${AWS_ACCOUNT_ID}-terraform-state-7736\""  >> backend.tf
      - echo "    key            = \"cloudops/terraform.tfstate\"" >> backend.tf
      - echo "    region         = \"${AWS_DEFAULT_REGION}\"" >> backend.tf
      - echo "    encrypt        = true" >> backend.tf
      - echo "    dynamodb_table = \"terraform-locks\"" >> backend.tf
      - echo "  }" >> backend.tf
      - echo "}" >> backend.tf
      - terraform force-unlock 5ccae578-acd3-8f0b-647e-ff02b6be8439 -force || true
      - echo Creating terraform.tfvars...
      - echo "aws_region = \"${AWS_DEFAULT_REGION}\"" > terraform.tfvars
      - echo "environment = \"demo\"" >> terraform.tfvars
      - echo "cluster_name = \"cloudops-demo\"" >> terraform.tfvars
      - echo "kubernetes_version = \"1.27\"" >> terraform.tfvars
      - echo "db_name = \"cloudops_demo\"" >> terraform.tfvars
      - echo "db_username = \"postgres\"" >> terraform.tfvars
      - echo "db_password = \"${DB_PASSWORD}\"" >> terraform.tfvars
      - echo Initializing Terraform...
      - terraform init
      - echo "Checking for existing conflicting resources..."
      - |
        # Clean up existing resources that might conflict (in proper order)
        echo "Checking for existing EKS addon (aws-ebs-csi-driver)..."
        # Attempts to delete the addon. '|| echo' prevents the script from failing
        # if the addon doesn't exist, which is expected for a clean state.
        aws eks delete-addon --cluster-name cloudops-demo --addon-name aws-ebs-csi-driver --region ${AWS_DEFAULT_REGION} || echo "EKS addon 'aws-ebs-csi-driver' not found or already deleted."
      
        echo "Waiting 30 seconds for addon deletion to propagate..."
        sleep 30 # Give AWS time to process the deletion before proceeding.
      
        echo "Checking for existing IAM role policy attachments for Load Balancer Controller..."
        # Detaches the policy from the role. The policy must be detached before the role can be deleted.
        aws iam detach-role-policy --role-name cloudops-demo-aws-load-balancer-controller --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/cloudops-demo-aws-load-balancer-controller || echo "Load Balancer Controller policy attachment not found or already detached."
      
        echo "Checking for existing IAM role for Load Balancer Controller..."
        # Deletes the role.
        aws iam delete-role --role-name cloudops-demo-aws-load-balancer-controller || echo "Load Balancer Controller IAM role not found or already deleted."
      
        echo "Checking for existing IAM policy for Load Balancer Controller..."
        # Deletes the policy. Policies can only be deleted after they are no longer attached to any roles.
        aws iam delete-policy --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/cloudops-demo-aws-load-balancer-controller || echo "Load Balancer Controller IAM policy not found or already deleted."
      
        echo "Existing resource cleanup completed."

  build:
    commands:
      - echo Starting Terraform ${TERRAFORM_ACTION}...
      - |
        case "${TERRAFORM_ACTION}" in
          "plan")
            echo "Running terraform plan..."
            terraform plan -out=tfplan -var-file=terraform.tfvars
            ;;
          "apply")
            echo "Running terraform plan and apply..."
            terraform plan -out=tfplan -var-file=terraform.tfvars
            terraform apply -auto-approve tfplan
            ;;
          "destroy")
            echo "Running terraform destroy..."
            terraform destroy -auto-approve -var-file=terraform.tfvars
            ;;
          *)
            echo "Invalid TERRAFORM_ACTION: ${TERRAFORM_ACTION}"
            echo "Valid options: plan, apply, destroy"
            exit 1
            ;;
        esac

  post_build:
    commands:
      - echo Terraform ${TERRAFORM_ACTION} completed successfully!
      - |
        if [ "${TERRAFORM_ACTION}" = "apply" ]; then
          echo "=== Infrastructure Outputs ==="
          terraform output
          echo "=== Setting up kubectl ==="
          aws eks update-kubeconfig --region ${AWS_DEFAULT_REGION} --name cloudops-demo
          kubectl get nodes
        fi

artifacts:
  files:
    - tfplan
    - "*.tf"
    - terraform.tfvars
    - terraform.tfstate.backup
  base-directory: terraform
  name: terraform-artifacts

cache:
  paths:
    - terraform/.terraform/**/*
