apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudops-demo
  labels:
    app: cloudops-demo
type: Opaque
data:
  # Base64 encoded values
  # password -> cGFzc3dvcmQ=
  # postgres -> cG9zdGdy
  POSTGRES_PASSWORD: Y2hhbmdlbWUtc2VjdXJlLXBhc3N3b3JkLTEyMw==
  POSTGRES_USER: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlbWUtc2VjdXJlLXBhc3N3b3JkLTEyMw==
